#!/usr/bin/env python3.7

import sys
import argparse
import requests
import json

parser = argparse.ArgumentParser(description='Copy HTML page to a file')
parser.add_argument('url', help='The url to write the page out')
parser.add_argument('filename', help='The destination file')
parser.add_argument('--content-type', '-c', default='html', choices=['html', 'json'], help='To select the format')

args = parser.parse_args()

res = requests.get(args.url)

if res.status_code == 200:
    with open(args.filename, 'w') as f:
        if args.content_type == 'json':
            content = json.dumps(res.json())
            f.write(content)
        else:
            f.write(res.text)



